AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  
  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5


Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: ../src
      FunctionName: main
      Description: >-
        An Amazon S3 trigger that retrieves metadata for the object that has
        been updated.
      MemorySize: 128
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref TestBucket
            Events:
            - 's3:ObjectCreated:Put'
      Environment:
        Variables:
          REGION: "ap-northeast-1"
          S3_ENDPOINT: "http://localstack:4572"
          TARGET_S3: "bucket-example-convert"


  TestBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "bucket-example"
  TestBucketConvert:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "bucket-example-convert"