version: 0.2

env:
  variables:
    DOCKER_COMPOSE_VERSION: "1.19.0"

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y zip unzip make
      - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go get -u github.com/awslabs/aws-sam-local
  build:
    commands:
      - make test-integration
  post_build:
    commands:
      - make deploy