version: '3'

services:
  localstack:
    container_name: localstack-example
    image: localstack/localstack
    ports:
    - "4572:4572"
    environment:
    - DEFAULT_REGION=ap-northeast-1
    - SERVICES=s3
    - DOCKER_HOST=unix:///var/run/docker.sock
    - HOSTNAME_EXTERNAL=localstack