version: '3'

services:
  localstack:
    container_name: localstack-example
    image: localstack/localstack
    ports:
    - "4572:4572"
    environment:
    - AWS_ACCESS_KEY_ID=dummy
    - AWS_SECRET_ACCESS_KEY=dummy
    - AWS_CBOR_DISABLE=true
    - DEFAULT_REGION=ap-northeast-1
    - SERVICES=s3
    - DEBUG=${DEBUG- }
    - DATA_DIR=${DATA_DIR- }
    - DOCKER_HOST=unix:///var/run/docker.sock
    - HOSTNAME_EXTERNAL=localstack
    volumes:
    - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    - "/var/run/docker.sock:/var/run/docker.sock"