AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: ../src
      FunctionName: main
      Description: >-
        An Amazon S3 trigger that retrieves metadata for the object that has
        been updated.
      MemorySize: 128
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 's3:GetObject'
          - 's3:PutObject'
          Resource: "arn:aws:s3:::bucket-example-*"
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref TestBucket
            Events:
            - 's3:ObjectCreated:Put'

  TestBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "bucket-example-staging"
  TestBucketConvert:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "bucket-example-convert-staging"